plugins {
    id 'java'
    id 'idea'
    id 'com.gradleup.shadow' version '8.3.6'
}

group = 'me.eastrane'
version = "${version}"

idea {
    module {
        downloadJavadoc = true
    }
}

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven {
        name 'codemc'
        url 'https://repo.codemc.org/repository/maven-public/'
    }
    maven {
        name = "maxhenkel"
        url = "https://maven.maxhenkel.de/repository/public/"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:${paperApiVersion}")
    implementation("org.bstats:bstats-bukkit:${bstatsVersion}")
    compileOnly("net.skinsrestorer:skinsrestorer-api:${skinsrestorerApiVersion}")
    compileOnly("de.maxhenkel.voicechat:voicechat-api:${voicechatApiVersion}")
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = targetJavaVersion
}

shadowJar {
    dependencies {
        relocate("org.bstats", "me.eastrane.eastzombies.dependencies.bstats")
    }

    //destinationDirectory = file("D:\\minecraft\\admin\\localhost\\plugins")
    archiveFileName = "${project.name}-${project.version}.jar"
}

tasks.build.dependsOn tasks.shadowJar

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}