name: EastZombies
version: '${version}'
main: me.eastrane.EastZombies
api-version: '1.20'
author: EastRane
softdepend:
  - "SkinsRestorer"
commands:
  eastzombies:
    description: Main command
    usage: /eastzombies
    aliases: [ez]